# Generated by Django 4.2.5 on 2023-11-05 15:04

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Email_Id', models.CharField(max_length=35)),
                ('Phone_No', models.CharField(default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('userid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('trainno', models.DecimalField(decimal_places=0, max_digits=2)),
                ('train_name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(default=myapp.models.default_date)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('Passenger_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
                ('Phone_No', models.CharField(default='', max_length=10, null=True)),
                ('Ticket_No', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('Station_Code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Station_Name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Stoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_No', models.IntegerField()),
                ('Station_Code', models.CharField(max_length=5)),
                ('Arrival_Time', models.TimeField(null=True)),
                ('Departure_Time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Train_No', models.IntegerField()),
                ('Username', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Train_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Seat_Sleeper', models.IntegerField()),
                ('Seat_FirstClass_AC', models.IntegerField()),
                ('Seat_SecondClass_AC', models.IntegerField()),
                ('Seat_Normal', models.IntegerField()),
                ('Foodavailability', models.CharField(default='N', max_length=1)),
                ('On_Sunday', models.CharField(default='N', max_length=1)),
                ('On_Monday', models.CharField(default='N', max_length=1)),
                ('On_Tuesday', models.CharField(default='N', max_length=1)),
                ('On_Wednesday', models.CharField(default='N', max_length=1)),
                ('On_Thursday', models.CharField(default='N', max_length=1)),
                ('On_Friday', models.CharField(default='N', max_length=1)),
                ('On_Saturday', models.CharField(default='N', max_length=1)),
                ('dest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
