# Generated by Django 4.2.5 on 2023-11-05 15:09

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Date_of_Journey',
            field=models.DateField(default=myapp.models.default_date),
        ),
        migrations.AddField(
            model_name='train',
            name='source',
            field=models.CharField(default='Varanasi', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(),
        ),
    ]
