# Generated by Django 4.2.5 on 2023-11-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_train_no_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='no_of_seats_rem',
            field=models.IntegerField(default=50),
        ),
    ]
