# Generated by Django 4.2.5 on 2023-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_train_no_of_seats_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='ticket_price',
            field=models.IntegerField(default=2000),
        ),
    ]
