# Generated by Django 4.2.5 on 2023-11-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_train_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
