# Generated by Django 4.2.5 on 2023-11-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_bookings_date_alter_bookings_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='userid',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
