# Generated by Django 4.2.5 on 2023-11-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_bookings_userid_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
