# Generated by Django 4.2.5 on 2023-11-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bookings_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.ForeignKey(default='ab@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
