# Generated by Django 4.2.5 on 2023-11-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_bookings_user_id_bookings_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='email',
            new_name='user_id',
        ),
    ]
