# Generated by Django 4.2.5 on 2023-11-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_bookings_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user_id',
        ),
    ]
