# Generated by Django 4.2.5 on 2023-11-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_bookings_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='email',
            new_name='email_id',
        ),
    ]
