# Generated by Django 4.2.5 on 2023-11-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_bookings_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='email_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.user'),
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
    ]
