# Generated by Django 4.2.5 on 2023-11-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_bookings_user_id_alter_bookings_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='email_id',
        ),
    ]
