# Generated by Django 4.2.5 on 2023-11-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_bookings_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='dest',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='nos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(blank=True, choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='train_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='trainno',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
